import { isWindows } from "../platform";

/**
 * Generates a bash script for the Claude Code statusline.
 * The script reads session JSON from stdin and combines it with
 * block usage data from the dashboard API.
 */
export function generateStatuslineScript(port: number): string {
  if (isWindows) {
    return `echo "Statusline requires macOS or Linux"`;
  }

  return `#!/usr/bin/env bash
# Claude Code Statusline — Usage Monitor
# Generated by velocity dashboard
# Reads session JSON from stdin, fetches block usage from dashboard API

set -euo pipefail

# ── Colors ──────────────────────────────────────
RESET="\\033[0m"
DIM="\\033[2m"
BOLD="\\033[1m"
CYAN="\\033[36m"
GREEN="\\033[32m"
YELLOW="\\033[33m"
RED="\\033[31m"
MAGENTA="\\033[35m"
WHITE="\\033[97m"
BAR_FILL="\\033[42m"     # green bg
BAR_EMPTY="\\033[100m"   # gray bg

# ── Check jq ────────────────────────────────────
if ! command -v jq &>/dev/null; then
  echo -e "\${DIM}statusline: install jq for usage stats\${RESET}"
  exit 0
fi

# ── Read session JSON from stdin ────────────────
SESSION_JSON=""
if [ ! -t 0 ]; then
  SESSION_JSON=$(cat)
fi

# Parse session fields (with defaults)
MODEL=$(echo "\${SESSION_JSON:-{}}" | jq -r '.model // "unknown"' 2>/dev/null || echo "unknown")
CONTEXT_PCT=$(echo "\${SESSION_JSON:-{}}" | jq -r '.context_window_percent // 0' 2>/dev/null || echo "0")
SESSION_COST=$(echo "\${SESSION_JSON:-{}}" | jq -r '.session_cost // 0' 2>/dev/null || echo "0")

# Shorten model name
case "$MODEL" in
  *opus*)   MODEL_SHORT="Opus" ;;
  *sonnet*) MODEL_SHORT="Sonnet" ;;
  *haiku*)  MODEL_SHORT="Haiku" ;;
  *)        MODEL_SHORT="$MODEL" ;;
esac

# ── Fetch block usage from dashboard ────────────
API_JSON=$(curl -sf "http://localhost:${port}/api/statusline" 2>/dev/null || echo "")

if [ -z "$API_JSON" ]; then
  # Dashboard not running — show session-only data
  printf "%b[%s]%b %s%% ctx | %b\\$%.2f%b session" \\
    "$CYAN" "$MODEL_SHORT" "$RESET" \\
    "$CONTEXT_PCT" \\
    "$GREEN" "$SESSION_COST" "$RESET"
  exit 0
fi

# Parse API response
BLOCK_COST=$(echo "$API_JSON" | jq -r '.block.cost // 0')
BLOCK_SESSIONS=$(echo "$API_JSON" | jq -r '.block.sessions // 0')
BLOCK_OUTPUT_TOKENS=$(echo "$API_JSON" | jq -r '.block.outputTokens // 0')
BLOCK_INPUT_TOKENS=$(echo "$API_JSON" | jq -r '.block.inputTokens // 0')
RESETS_AT=$(echo "$API_JSON" | jq -r '.block.resetsAt // empty')
PLAN=$(echo "$API_JSON" | jq -r '.plan // empty')
BLOCK_BUDGET=$(echo "$API_JSON" | jq -r '.blockBudget // 0')

# ── Plan type detection ────────────────────────
IS_MAX=false
case "\${PLAN:-}" in
  pro|max5x|max20x) IS_MAX=true ;;
esac

# ── Budget lookup (API users only) ─────────────
BUDGET=""
if [ "$IS_MAX" = "false" ]; then
  if [ "\${BLOCK_BUDGET:-0}" != "0" ]; then
    BUDGET="$BLOCK_BUDGET"
  fi
fi

# ── Reset countdown ─────────────────────────────
RESET_STR=""
if [ -n "\${RESETS_AT:-}" ]; then
  NOW_TS=$(date +%s)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    RESET_TS=$(date -j -f "%Y-%m-%dT%H:%M:%S" "\${RESETS_AT%%.*}" +%s 2>/dev/null || echo "0")
  else
    RESET_TS=$(date -d "$RESETS_AT" +%s 2>/dev/null || echo "0")
  fi
  DIFF=$((RESET_TS - NOW_TS))
  if [ "$DIFF" -gt 0 ]; then
    HOURS=$((DIFF / 3600))
    MINS=$(( (DIFF % 3600) / 60 ))
    if [ "$HOURS" -gt 0 ]; then
      RESET_STR="\${HOURS}h\${MINS}m"
    else
      RESET_STR="\${MINS}m"
    fi
  fi
fi

# ── Format token count ─────────────────────────
format_tokens() {
  local t=$1
  if [ "$t" -ge 1000000 ]; then
    printf "%.1fM" "$(echo "scale=1; $t / 1000000" | bc)"
  elif [ "$t" -ge 1000 ]; then
    printf "%.1fK" "$(echo "scale=1; $t / 1000" | bc)"
  else
    printf "%d" "$t"
  fi
}

# ── Build output ────────────────────────────────
# Session info
OUTPUT=""
OUTPUT+="\${CYAN}\${BOLD}[\${MODEL_SHORT}]\${RESET} "
OUTPUT+="\${CONTEXT_PCT}% ctx | "
OUTPUT+="\${GREEN}\\$$(printf '%.2f' "\${SESSION_COST}")\${RESET} session"

# Block info — Max plans show tokens, API users show dollars
if [ "$IS_MAX" = "true" ]; then
  OUT_FMT=$(format_tokens "$BLOCK_OUTPUT_TOKENS")
  IN_FMT=$(format_tokens "$BLOCK_INPUT_TOKENS")
  OUTPUT+=" | Block: \${YELLOW}\${OUT_FMT}\${RESET} out \${DIM}\${IN_FMT} in\${RESET}"
  OUTPUT+=" (\${BLOCK_SESSIONS} sessions)"
else
  OUTPUT+=" | Block: \${YELLOW}\\$$(printf '%.2f' "\${BLOCK_COST}")\${RESET}/5h"

  if [ -n "$BUDGET" ]; then
    # Show progress bar for API users with budget
    PCT=$(echo "scale=0; \${BLOCK_COST} * 100 / \${BUDGET}" | bc 2>/dev/null || echo "0")
    [ "$PCT" -gt 100 ] && PCT=100

    BAR_WIDTH=10
    FILLED=$((PCT * BAR_WIDTH / 100))
    EMPTY=$((BAR_WIDTH - FILLED))

    BAR=""
    for ((i=0; i<FILLED; i++)); do BAR+="\${BAR_FILL} \${RESET}"; done
    for ((i=0; i<EMPTY; i++)); do BAR+="\${BAR_EMPTY} \${RESET}"; done

    # Color based on usage level
    if [ "$PCT" -ge 90 ]; then
      PCT_COLOR="$RED"
    elif [ "$PCT" -ge 70 ]; then
      PCT_COLOR="$YELLOW"
    else
      PCT_COLOR="$GREEN"
    fi

    OUTPUT+=" \${DIM}\\xe2\\x96\\x90\${RESET}\${BAR}\${DIM}\\xe2\\x96\\x8c\${RESET} \${PCT_COLOR}\${PCT}%\${RESET}"
  else
    OUTPUT+=" (\${BLOCK_SESSIONS} sessions)"
  fi
fi

# Reset countdown
if [ -n "$RESET_STR" ]; then
  OUTPUT+=" | \${DIM}resets \${RESET_STR}\${RESET}"
fi

echo -e "$OUTPUT"
`;
}
